### ISSUE TITLE
[BUG] rapids-colab.sh script fails to properly install the libraries in several instances

### ISSUE THREAD

**Issue by taureandyernv** [rapidsai/notebooks-contrib#232]
**Describe the bug**
Colab script has several new issues:
1. when installing 0.11 nightlies, cudf is installed as `=.10 `
1. when installed a stable release, like `0.10`, the script fails
1. when installing xgboost, the script fails with a 404 error
1. when all libraries are installed in 0.11, cudf and cugraph throw Attribute errors around features that have been removed for 0.11
- cudf errror: AttributeError: type object 'cudf._lib.gpuarrow.CudaRecordBatchStreamReader' has no attribute '__reduce_cython__', which was removed in https://github.com/rapidsai/cudf/commit/e5192de83d7d3a568796cadfdd4159236d6ec665
- cugraph error (coming soon)

**Comment by taureandyernv** [comment]
Creating a PR for fixing 1,2, and 3 https://github.com/rapidsai/notebooks-contrib/pull/233.  May do a quick merge to get users working in Colab with v0.10 and we can fix 0.11 after.  Thoughts @randerzander ?
